### ISSUE TITLE
Personal Credentials Overrride Params

### ISSUE THREAD

**Issue by CheeseL0ver** [frieser/nordigen-go-lib#7]
https://github.com/frieser/nordigen-go-lib/blob/a88404b239379815866a47ea7c209987d3ad2b02/client.go#L57
https://github.com/frieser/nordigen-go-lib/blob/a88404b239379815866a47ea7c209987d3ad2b02/client.go#L58

I believe the passed args are overwritten by hard coded stored creds.

**Comment by CheeseL0ver** [comment]
Also may be a good idea to create a new set of tokens after the fix is applied.

**Comment by frieser** [comment]
omg, yes, my mistake.
